### ISSUE TITLE
Change text height of barcode

### ISSUE THREAD

**Issue by maphongba008** [helpkang/react-native-ksi-barcode#2]
Is there anyway to change the text height of barcode? I want to scale the height of text to full parent (the green one).
![screen shot 2016-11-01 at 10 37 16 am](https://cloud.githubusercontent.com/assets/8359203/19878841/d8f00f5c-a01f-11e6-82e4-3dca146f6a4a.png)

**Comment by helpkang** [comment]
Hi.
I have problem understand.

This is soultion code.

You get parent view height from onLayout event.

`
export default class BarcodeTest extends Component {
    state = {
        height: 10, //default height
    }
    render() {
        return (

```
        <View style={styles.container}
            onLayout={(event) => {
                const {height} = event.nativeEvent.layout
                this.setState({ height })
            } }
            >
            <Barcode text="ME2T53DPC" style={{ fontSize: this.state.height }} />
        </View>
    );
}
```

}
`
