### ISSUE TITLE
Cannot create barcode

### ISSUE THREAD

**Issue by maphongba008** [helpkang/react-native-ksi-barcode#3]
I can create barcode for long text like: 11111111
But if there are many 9 like: 99999999, the barcode can't not be created (see the pic below, the top is 11111111 and the bottom is 99999999)
How can I fix it?
![screen shot 2016-11-09 at 1 03 15 pm](https://cloud.githubusercontent.com/assets/8359203/20128761/2be07b9e-a67d-11e6-9e26-317e6b490480.png)

My code:
```
 <KsiBarcode text='11111111'/>
 <KsiBarcode text='99999999'/>
```

**Comment by helpkang** [comment]
soon i will mast fix it. 
this used my application. ^^;

**Comment by helpkang** [comment]
solved this problem.
